server {
  listen 80;
  listen [::]:80;
  server_name langclaw.43-129-56-85.sslip.io;

  location / {
    return 301 https://$host$request_uri;
  }
}

server {
  listen 443 ssl;
  listen [::]:443 ssl;
  server_name langclaw.43-129-56-85.sslip.io;

  ssl_certificate /etc/letsencrypt/live/langclaw.43-129-56-85.sslip.io/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/langclaw.43-129-56-85.sslip.io/privkey.pem;

  location / {
    return 301 https://langclaw-sui-walrus.vercel.app$request_uri;
  }
}
